data:extend({
	{
		type = "int-setting",
		name = "wood-walls-fuelvalue",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0,
		maximum_value = 100,
		order = "aa",
	},
	{
		type = "int-setting",
		name = "wood-walls-wall-cost",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 100,
		order = "ab",
	},
	{
		type = "int-setting",
		name = "wood-walls-wall-output",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 100,
		order = "ac",
	},
	{
		type = "int-setting",
		name = "wood-walls-hp",
		setting_type = "startup",
		default_value = 150,
		minimum_value = 10,
		maximum_value = 1000,
		order = "ad",
	},
	{
		type = "bool-setting",
		name = "wood-walls-disable-wall",
		setting_type = "startup",
		default_value = false,
		order = "ae",
	},
})
